unit DispCardDataDM;

interface

uses
  SysUtils, Classes, DB, ADODB, Common, dxmdaset, Forms;

type
  TDispCardDataDM = class(TDataModule)
    dsSItems: TDataSource;
    qSItems: TADOQuery;
    QStation: TADOQuery;
    QStationStationID: TAutoIncField;
    QStationName: TWideStringField;
    dsStation: TDataSource;
    dsTran: TDataSource;
    qTran: TADOQuery;
    qCust: TADOQuery;
    dsCust: TDataSource;
    dsACard: TDataSource;
    qACard: TADOQuery;
    qACardLProd1: TStringField;
    qACardLProd2: TStringField;
    qACardLProd3: TStringField;
    qACardLProd4: TStringField;
    qACardLProd5: TStringField;
    qACardLProd6: TStringField;
    qACardLProd7: TStringField;
    qACardLProd8: TStringField;
    qACardLProd9: TStringField;
    qACardLProd10: TStringField;
    qApproval: TADOQuery;
    dsApproval: TDataSource;
    qApprovalAPPROVALID: TAutoIncField;
    qApprovalAPPROVALACARDID: TIntegerField;
    qApprovalAPPROVALSTATIONID: TIntegerField;
    qApprovalAPPROVALAMOUNT: TFloatField;
    qApprovalAPPROVALCODE: TWideStringField;
    qApprovalINSDT: TDateTimeField;
    qApprovalUPDDT: TDateTimeField;
    qApprovalINSUSR: TIntegerField;
    qApprovalUPDUSR: TIntegerField;
    qACardACARDID: TAutoIncField;
    qACardACARDCODE: TWideStringField;
    qACardCUSTOMERID: TIntegerField;
    qACardISSUEDATE: TDateTimeField;
    qACardEXPIREDATE: TDateTimeField;
    qACardMETERBOOLEAN: TBooleanField;
    qACardPINBOOLEAN: TBooleanField;
    qACardINSDT: TDateTimeField;
    qACardUPDDT: TDateTimeField;
    qACardINSUSR: TIntegerField;
    qACardUPDUSR: TIntegerField;
    qACardSTARTDATE: TDateTimeField;
    qACardVTYPEID: TIntegerField;
    qACardCREATEBOOLEAN: TBooleanField;
    qACardBLACKLISTBOOLEAN: TBooleanField;
    qACardBLACKLISTDATE: TDateTimeField;
    qACardBLACKLISTUSR: TIntegerField;
    qACardBLACKLISTNOTES: TWideStringField;
    qACardIGROUPID1: TIntegerField;
    qACardIGROUPID2: TIntegerField;
    qACardIGROUPID3: TIntegerField;
    qACardIGROUPID4: TIntegerField;
    qACardDAYAMOUNT: TFloatField;
    qACardMONTHAMOUNT: TFloatField;
    qACardREGNO: TWideStringField;
    qACardACARDHOLDER: TWideStringField;
    qACardISACTIVE: TBooleanField;
    qACardEXPIREPHDATE: TDateTimeField;
    qACardEXPIRELODATE: TDateTimeField;
    qACardIGROUPID5: TIntegerField;
    qACardEMPLOYEESID: TIntegerField;
    qACardNEWCARDBOOLEAN: TBooleanField;
    qACardNEWCARDID: TIntegerField;
    qACardCARDHASEMPNAME: TBooleanField;
    qACardACARDCODENUM: TIntegerField;
    qACardINACTIVEDATE: TDateTimeField;
    qACardINACTIVEUSR: TIntegerField;
    qACardINACTIVENOTES: TWideStringField;
    qACardIGROUPID6: TIntegerField;
    qACardIGROUPID7: TIntegerField;
    qACardIGROUPID8: TIntegerField;
    qACardIGROUPID9: TIntegerField;
    qACardIGROUPID10: TIntegerField;
    qACardCOSTCENTERID: TIntegerField;
    qACardAcardCodeFull: TWideStringField;
    memStation: TdxMemData;
    memStationCardKey: TIntegerField;
    dsmemStation: TDataSource;
    ADOQuery1: TADOQuery;
    ADOQuery1AcardAcardId: TAutoIncField;
    ADOQuery1AcardREGNO: TWideStringField;
    ADOQuery1AcardAcardCode: TWideStringField;
    ADOQuery1AcardAcardCodeFull: TWideStringField;
    DataSource1: TDataSource;
    ADOQuery1AcardId: TIntegerField;
    qCustCUSTOMERID: TAutoIncField;
    qCustNAME: TWideStringField;
    qCustSTREET: TWideStringField;
    qCustZIP: TWideStringField;
    qCustCITY: TWideStringField;
    qCustAFM: TWideStringField;
    qCustDOY: TWideStringField;
    qCustSTARTDATE: TDateTimeField;
    qCustAREAID: TIntegerField;
    qCustLOCATIONID: TIntegerField;
    qCustCGROUPID: TIntegerField;
    qCustCCLASSID: TIntegerField;
    qCustCREDITAMOUNT: TFloatField;
    qCustINSDT: TDateTimeField;
    qCustUPDDT: TDateTimeField;
    qCustINSUSR: TIntegerField;
    qCustUPDUSR: TIntegerField;
    qCustPROFESSION: TWideStringField;
    qCustBRANCHID: TIntegerField;
    qCustSAPCODE: TWideStringField;
    qCustISACTIVE: TBooleanField;
    qCustSALESMENID: TIntegerField;
    qCustDIAKID: TIntegerField;
    qCustISTEST: TBooleanField;
    qCustISCONS: TBooleanField;
    qCustAREABID: TIntegerField;
    qCustDATEPHEND: TDateTimeField;
    qCustDATELOEND: TDateTimeField;
    qCustHASDETAILEMP: TBooleanField;
    qCustALLCARDSTOBL: TBooleanField;
    qCustALLCARDSTOBLDATE: TDateTimeField;
    qCustALLCARDSTOBLSYSDATE: TDateTimeField;
    qCustALLCARDSTOBLUSR: TIntegerField;
    qCustCUSTOMEROFF: TBooleanField;
    qCustCUSTOMEROFFDATE: TDateTimeField;
    qCustCUSTOMEROFFSYSDATE: TDateTimeField;
    qCustCUSTOMEROFFUSR: TIntegerField;
    qCustCARDHASEMPNAME: TBooleanField;
    qCustDATEEND: TDateTimeField;
    qCustCompanyTypeId: TIntegerField;
    qCustGarantieId: TIntegerField;
    qCustGarantieAmount: TBCDField;
    qCustComments: TMemoField;
    qTranMerchantMerchantId: TIntegerField;
    qTranMerchantName: TWideStringField;
    qTranMerchantStreet: TWideStringField;
    qTranMerchantZip: TWideStringField;
    qTranMerchantCity: TWideStringField;
    qTranMerchantAFM: TWideStringField;
    qTranMerchantDOY: TWideStringField;
    qTranMerchantIsTest: TBooleanField;
    qTranMerchantAreaId: TIntegerField;
    qTranMerchantSAPCode: TWideStringField;
    qTranMerchantMerchantCode: TWideStringField;
    qTranMerchantSalesMenId: TIntegerField;
    qTranMerchantDeleted: TBooleanField;
    qTranMerchantInActive: TBooleanField;
    qTranMerchantStopSales: TBooleanField;
    qTranStationStationId: TIntegerField;
    qTranStationName: TWideStringField;
    qTranStationStreet: TWideStringField;
    qTranStationZIP: TWideStringField;
    qTranStationCity: TWideStringField;
    qTranStationAreaId: TIntegerField;
    qTranStationSalesMenId: TIntegerField;
    qTranStationDeleted: TBooleanField;
    qTranStationInActive: TBooleanField;
    qTranStationStopSales: TBooleanField;
    qTranTerminalTerminalCode: TWideStringField;
    qTranTerminalTerminalId: TIntegerField;
    qTranTerminalSerialNo: TWideStringField;
    qTranCUSTOMERCUSTOMERId: TIntegerField;
    qTranCUSTOMERName: TWideStringField;
    qTranCUSTOMERZip: TWideStringField;
    qTranCUSTOMERStreet: TWideStringField;
    qTranCUSTOMERCity: TWideStringField;
    qTranCUSTOMERAFM: TWideStringField;
    qTranCUSTOMERDOY: TWideStringField;
    qTranCUSTOMERAreaId: TIntegerField;
    qTranCUSTOMERCGroupId: TIntegerField;
    qTranCUSTOMERCClassId: TIntegerField;
    qTranCUSTOMERBranchId: TIntegerField;
    qTranCUSTOMERSAPCode: TWideStringField;
    qTranCUSTOMERIsActive: TBooleanField;
    qTranCUSTOMERSalesMenId: TIntegerField;
    qTranCUSTOMERIsTest: TBooleanField;
    qTranCUSTOMERAreaBId: TIntegerField;
    qTranCUSTOMERHASDETAILEMP: TBooleanField;
    qTranCUSTOMERCUSTOMEROFF: TBooleanField;
    qTranTRANTRANDATE: TDateTimeField;
    qTranTRANACARDID: TIntegerField;
    qTranTRANMerchantId: TIntegerField;
    qTranTRANStationId: TIntegerField;
    qTranTRANTerminalId: TIntegerField;
    qTranTRANAmount: TFloatField;
    qTranTRANSitemId: TIntegerField;
    qTranTRANQuantity: TFloatField;
    qTranTRANIsAuto: TBooleanField;
    qTranTRANStationUPD: TBooleanField;
    qTranTRANACARDUPD: TBooleanField;
    qTranTRANIsVoid: TBooleanField;
    qTranTRANBatchNo: TIntegerField;
    qTranTRANCommissionUpd: TBooleanField;
    qTranTRANStationUPDBT: TIntegerField;
    qTranTRANAcardUPDBT: TIntegerField;
    qTranTRANCommissionUPDBT: TIntegerField;
    qTranTRANTranTime: TDateTimeField;
    qTranTRANIsTyped: TBooleanField;
    qTranTRANDiscountUPD: TBooleanField;
    qTranTRANDiscountUPDBT: TIntegerField;
    qTranTRANDisQuantity: TFloatField;
    qTranTRANDisAmount: TFloatField;
    qTranTRANPelaDailyUPD: TBooleanField;
    qTranTRANPelaDailyUPDBT: TIntegerField;
    qTranACARDACARDID: TIntegerField;
    qTranACARDACARDCODE: TWideStringField;
    qTranACARDCustimerId: TIntegerField;
    qTranACARDVTypeId: TIntegerField;
    qTranACARDREGNO: TWideStringField;
    qTranACARDACARDHOLDER: TWideStringField;
    qTranACARDIsActive: TBooleanField;
    qTranACARDEMPLOYEESID: TIntegerField;
    qTranACARDCostCenterId: TIntegerField;
    qTranVTYPEVTYPEID: TIntegerField;
    qTranVTYPEDescr: TWideStringField;
    qTranREGNOSEQREGNOSEQID: TIntegerField;
    qTranREGNOSEQREGNO: TWideStringField;
    qTranTRANTRANID: TIntegerField;
    qTranTRANKMBEFORE: TIntegerField;
    qTranTRANKMAFTER: TIntegerField;
    qTranTRANREFSTR: TWideStringField;
    qTranTRANUNITPRICE: TFloatField;
    qTranSITEMCODEINTERMINAL: TIntegerField;
    qTranSITEMDESCR: TWideStringField;
    qTranSITEMIGROUPID: TIntegerField;
    qTranIGROUPNAME: TWideStringField;
    qTranCostCenterCCName: TWideStringField;
    qTranCostCenterCCNameFull: TWideStringField;
    memStationAcardId: TIntegerField;
    qSItemsId: TAutoIncField;
    qSItemsName: TWideStringField;
    qSItemsBITNO: TIntegerField;
    qSItemsPOSOSTO: TFloatField;
    qSItemsInsUsr: TIntegerField;
    qSItemsInsDT: TDateTimeField;
    qSItemsUpdUsr: TIntegerField;
    qSItemsUpdDT: TDateTimeField;
    qSItemsDeleted: TBooleanField;
    qSItemsDelUsr: TIntegerField;
    qSItemsDelDT: TDateTimeField;
    qSItemsInActive: TBooleanField;
    qSItemsInActiveUsr: TIntegerField;
    qSItemsInActiveDt: TDateTimeField;
    qSItemsUseKM: TBooleanField;
    qSItemsUseQuantity: TBooleanField;
    qSItemsCalcCons: TBooleanField;
    memStationDateFrom: TDateTimeField;
    procedure ADOQuery1CalcFields(DataSet: TDataSet);
    procedure memStationCalcFields(DataSet: TDataSet);
    procedure DataModuleCreate(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

implementation

uses DMain;

{$R *.dfm}

procedure TDispCardDataDM.ADOQuery1CalcFields(DataSet: TDataSet);
begin
  ADOQuery1AcardId.Value := ADOQuery1AcardAcardId.Value;
end;

procedure TDispCardDataDM.DataModuleCreate(Sender: TObject);
begin
  DMCreate(TForm(self));
  memStation.Active := True;
end;

procedure TDispCardDataDM.memStationCalcFields(DataSet: TDataSet);
begin
  memStationAcardId.Value := memStationCardKey.Value;
end;

end.
